name: Build

on: 
  push:
    branches: [ test ]
  pull_request:

jobs:
  KMC_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine Branch on Push
        run: echo "CURRENT_BRANCH=$(git branch --show-current)" >> $GITHUB_ENV
      - name: Use Branch
        run: echo ${{ env.CURRENT_BRANCH}}
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USER }}
      #    password: ${{ secrets.DOCKER_PASS }}
      #- name: Build Compose Containers
      #  run: cd ./compose && docker-compose -f docker-compose-kmc-mdb up -d
      
      - name: Remove Build Directory
        run: if test -d /itc/CryptoLib/build; then rm -rf /itc/CryptoLib/build; fi
      - name: Build Redhat CryptoLib
        run: |
          ls
          mkdir -p /itc/CryptoLib/build
          cd /itc/CryptLib/build
          
     # - name: Test KMC SA MGMT List 
     #   uses: nick-fields/retry@v2
     #   with:
     #     timeout_seconds: 15
     #     max_attempts: 3
     #     retry_on: error
     #     command: |
     #       docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' compose_kmc_1
     #       docker exec compose_kmc_1 /ammos/kmc-crypto-client/bin/kmc-sa-mgmt list

     # - name: Cleanup
     #   run: cd ./compose && docker-compose -f docker-compose-kmc-mdb down
