name: CryptoLib - RedHat - Build

on: 
  push:
    branches: [ test ]
  pull_request:

jobs:
  Redhat_Build:
    runs-on: ubuntu-latest
    container:
      image: rbrown00/redhattest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          
     # - name: Determine Branch on Push
     #   run: echo "CURRENT_BRANCH=$(git branch --show-current)" >> $GITHUB_ENV
     # - name: Use Branch
     #   run: echo ${{ env.CURRENT_BRANCH}}
     # - name: Login to Docker Hub
     #   uses: docker/login-action@v2
     #   with:
     #     username: ${{ secrets.DOCKER_USER }}
     #     password: ${{ secrets.DOCKER_PASS }}
     # - name: Build Compose Containers
     #   run: cd ./compose && docker-compose -f docker-compose-kmc-mdb up -d
        
     # - name: Remove Build Directory Redhat
     #   run: docker exec compose_redhat_1 bash -c 'if test -d /itc/CryptoLib/build; then rm -rf /itc/CryptoLib/build; fi'
        
     # - name: Build RedHat CryptoLib
     #   run: docker exec compose_redhat_1 bash -c 'cd /itc/CryptoLib/ && git checkout ${{ env.CURRENT_BRANCH }} && mkdir build && cd build && cmake -DDEBUG=1 -DMYSQL=1 -DLIBGCRYPT=1 -DKMCCRYPTO=1 -DENCTEST=1 ../ && make'
     # - name: Test RedHat CryptoLib 
     #   run: docker exec compose_redhat_1 bash -c 'cd/itc/CryptoLib/build && make test'   
     # - name: Test KMC SA MGMT List 
     #   uses: nick-fields/retry@v2
     #   with:
     #     timeout_seconds: 15
     #     max_attempts: 3
     #     retry_on: error
     #     command: |
     #       docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' compose_kmc_1
     #       docker exec compose_kmc_1 /ammos/kmc-crypto-client/bin/kmc-sa-mgmt list

      - name: Cleanup
        run: cd ./compose && docker-compose -f docker-compose-kmc-mdb down
