name: Build

on: 
  push:
    branches: [ test ]
  pull_request:

jobs:
  KMC_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build Compose Containers
        run: cd ./compose && docker-compose -f docker-compose-kmc-mdb up -d
  

      - name: Test
        run: |
          pwd 
          ls 
          docker ps -a
